=== ypbl/eip-lab1c/Product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:complexType name="ProductType">
        <xsd:sequence>
            <xsd:element name="ProductId" type="xsd:int"></xsd:element>
            <xsd:element name="ProductDescription" type="xsd:string"></xsd:element>
            <xsd:element name="ProductPrice" type="xsd:float"></xsd:element>
            <xsd:element name="ProductAmount" type="xsd:int"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
     <xsd:complexType name="ProductsType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="Product" type="ProductType"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="Products" type="ProductsType"/>
</xsd:schema>

=== ypbl/eip-lab1c/Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<Products  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://eexposit.perso.univ-pau.fr/content/xsd/Product.xsd">
    <Product>
        <ProductId>1</ProductId>
        <ProductDescription>smartphone</ProductDescription>
        <ProductPrice>500.00</ProductPrice>
        <ProductAmount>10</ProductAmount>
    </Product>
    <Product>
        <ProductId>2</ProductId>
        <ProductDescription>computer</ProductDescription>
        <ProductPrice>1200.00</ProductPrice>
        <ProductAmount>5</ProductAmount>
    </Product>
</Products>
